export const SET_WEB3_PROVIDER = 'SET_WEB3_PROVIDER';
export const SET_NETWORK_NAME = 'SET_NETWORK_NAME';
export const SET_ACCOUNT_ADDRESS = 'SET_ACCOUNT_ADDRESS';
export const SET_BLOCK_HEIGHT = 'SET_BLOCK_HEIGHT';
